on:
  push:
    branches: [ workflow-test ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World!"
      - run: pwd
      - run: cd ./src/data
      - run: pwd
