name: Update courses

on:
  push:
    branches: [ workflow-test ]
    # inputs:
      # reason:
        # description: 'Reason for manually triggering this workflow'
        # required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install bs4 requests
      - name: Run course update
        run: python3 ./src/data/courseDataUpdate.py
